### ISSUE TITLE
3.5.0 Deployment to GCP Cloud Run failed

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1254]
Deployment to [Google Cloud Run failed](https://github.com/micronaut-projects/micronaut-starter/blob/3.4.x/.github/workflows/release.yml#L263-L303) 

See. https://github.com/micronaut-projects/micronaut-starter/actions/runs/2387331635

logs: 

```
 io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2777)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1594)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:863)
	at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:94)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1680)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:352)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:190)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:320)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:295)
	at io.micronaut.starter.netty.Application.main(Application.java:23)
```

it looks like https://github.com/micronaut-projects/micronaut-core/issues/7144

But we have: 

https://github.com/micronaut-projects/micronaut-starter/blob/3.4.x/starter-gcp-function/build.gradle#L38-L43

**Comment by sdelamo** [comment]
@melix @graemerocher any idea what could have changed between 3.5.0 and 3.4.4 to cause this?
