### ISSUE TITLE
Cli Unable to create kotlin-maven project [JDK17]

### ISSUE THREAD

**Issue by onXoot** [micronaut-projects/micronaut-starter#1473]
java version:
```
root@pc:java -version

java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)
```
cli version:
```
root@pc:mn --version
Micronaut Version: 3.7.1
```
error:
```
root@pc:mn create-app mn-kotlin --build=maven --lang=kotlin
| Error Cannot invoke "io.micronaut.starter.options.TestFramework.isKotlinTestFramework()" because the return value of "io.micronaut.starter.options.Options.getTestFramework()" is null

```

**Comment by alvarosanchez** [comment]
Passing also `--test` makes it work. The error does not reproduce on Micronaut Launch since we seem to always pass a value for test framework.

**Comment by alvarosanchez** [comment]
```
$ mn create-app --build=maven --lang=kotlin com.example.demo -v -x                                                                                                                                                                                                                         | Error null
java.lang.NullPointerException
	at io.micronaut.starter.feature.test.Mockk.shouldApply(Mockk.java:78)
	at io.micronaut.starter.application.ContextFactory.lambda$createFeatureContext$0(ContextFactory.java:70)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.micronaut.starter.application.ContextFactory.createFeatureContext(ContextFactory.java:71)
	at io.micronaut.starter.application.generator.DefaultProjectGenerator.createGeneratorContext(DefaultProjectGenerator.java:114)
	at io.micronaut.starter.application.generator.DefaultProjectGenerator.generate(DefaultProjectGenerator.java:61)
	at io.micronaut.starter.cli.command.CreateCommand.generate(CreateCommand.java:131)
	at io.micronaut.starter.cli.command.CreateCommand.call(CreateCommand.java:118)
	at io.micronaut.starter.cli.command.CreateCommand.call(CreateCommand.java:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.micronaut.starter.cli.MicronautStarter.execute(MicronautStarter.java:115)
	at io.micronaut.starter.cli.MicronautStarter.main(MicronautStarter.java:101)
```
