### ISSUE TITLE
Snapshot to GCF

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1770]
```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. This is likely due to a bug in the user code. Error message: Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAM=256m -XX:MaxRAMPercentage=70
2023-05-03 22:00:58.791:INFO::main: Logging initialized @579ms to org.eclipse.jetty.util.log.StdErrLog
Error: Exception in thread "main" java.lang.UnsupportedClassVersionError: io/micronaut/gcp/function/http/HttpFunction has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.google.cloud.functions.invoker.runner.Invoker.loadFunctionClass(Invoker.java:272)
	at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:235)
	at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121)
. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.
Error: Process completed with exit code 1.
```

**Comment by graemerocher** [comment]
would probably disable this until they support JDK 17

**Comment by sdelamo** [comment]
They support Java 17 now https://cloud.google.com/functions/docs/concepts/java-runtime I think I have to fix it in the Google Cloud Console. I will be checking this today.
