### ISSUE TITLE
Project with r2dbc, micrometer, and database driver features fail with test-resources error.

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-starter#1960]
Create a starter [project with `r2dbc`, and database driver feature and a micrometer feature. It will crash if you run it, or execute the default test with the error:

```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.r2dbc.spi.ConnectionFactory] could not be loaded: Error instantiating bean of type  [io.r2dbc.spi.ConnectionFactoryOptions$Builder]

Message: Could not resolve placeholder ${auto.test.resources.r2dbc.datasources.default.options.protocol}
Path Taken: ConnectionFactory.connectionFactory(ConnectionFactoryOptions options) --> ConnectionFactory.connectionFactory([ConnectionFactoryOptions options]) --> ConnectionFactoryOptions.connectionFactoryOptions([Builder builder]) --> Builder.connectionFactoryOptionsBuilder([BasicR2dbcProperties basicR2dbcProperties])
	at app//io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921)
	at app//io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249)
	at app//io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
	at app//io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
	at app//io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
	at app//io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
...
```

The following Spock test run in `micronaut-starter` exposes this failure.

```groovy
    void "test dbFeature #dbFeature, r2dbc feature #r2dbcFeature and micrometer-prometheus"(
            String dbFeature, String r2dbcFeature
    ) {
        when:
        generateProject(Language.JAVA, BuildTool.GRADLE,
                [r2dbcFeature, dbFeature, "micrometer-prometheus"])
        String result = executeBuild(BuildTool.GRADLE, "test")

        then:
        result?.contains("BUILD SUCCESS")

        where:
        [dbFeature, r2dbcFeature] << [
                [PostgreSQL.NAME, MySQL.NAME, Oracle.NAME],
                [R2dbc.NAME, DataR2dbc.NAME] // fails for R2dbc.NAME, doesn't fail for DataR2dbc.NAME
        ].combinations()
    }

```

Note that running this test will fail with `data-r2dbc` as well unless you run it on a branch that has an unrelated fix for that. See #1959. The real issue is with `r2dbc` and not `data=-r2dbc`. I'm leaving this issue here on starter rather than `micronaut-test-resources` since I don't if it's a config problem starter needs to fix (and that's where my test will run).

**Comment by wetted** [comment]
@melix  Create a project with `mn create-app --build=gradle --jdk=17 --lang=java --test=spock --features=r2dbc,micrometer-prometheus,postgres com.example.demo`

add `runtimeOnly("io.r2dbc:r2dbc-pool")` dependency

**Comment by melix** [comment]
The issue is that the generated `application.properties` file misses an entry for the dialect. It should add:

```
r2dbc.datasources.default.dialect=postgres
```

**Comment by wetted** [comment]
> The issue is that the generated `application.properties` file misses an entry for the dialect. It should add:
> 
> ```
> r2dbc.datasources.default.dialect=postgres
> ```

OK. Thanks. I can make that change for generated apps.
