### ISSUE TITLE
Core and Platform to snapshot failed

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#2001]
https://github.com/micronaut-projects/micronaut-starter/actions/runs/5765751704/job/15632737459

```
 1 file changed, 14 insertions(+), 13 deletions(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.16.0/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.16.0/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
```

**Comment by timyates** [comment]
Think this is fixed by https://github.com/micronaut-projects/micronaut-starter/pull/2014
