### ISSUE TITLE
Generating a Kotlin application with KTOR results in an Application class for java

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#231]
Step to reproduce:

```
curl https://launch.micronaut.io/ktor-test.zip\?features\=ktor\&lang\=kotlin -o ktor-test.zip
unzip ktor-test.zip -d ktor-test
```

There are 2 application classes one in `src/main/java` and the other in `src/main/kotlin`

**Comment by graemerocher** [comment]
This causes the application to fail to compile with:

```
Caused by: java.lang.NullPointerException
        at org.jetbrains.kotlin.kapt3.base.incremental.TypeTreeVisitor.visitVariable(javacVisitors.kt:112)
        at org.jetbrains.kotlin.kapt3.base.incremental.TypeTreeVisitor.visitVariable(javacVisitors.kt:50)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:864)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at org.jetbrains.kotlin.kapt3.base.incremental.TypeTreeVisitor.visitMethod(javacVisitors.kt:92)
        at org.jetbrains.kotlin.kapt3.base.incremental.TypeTreeVisitor.visitMethod(javacVisitors.kt:50)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at org.jetbrains.kotlin.kapt3.base.incremental.TypeTreeVisitor.visitClass(javacVisitors.kt:75)
```

**Comment by graemerocher** [comment]
Hmm can't reproduce this now
