### ISSUE TITLE
`:starter-api:test` failed with `Unsupported JDK version: 13.`

### ISSUE THREAD

**Issue by chenrui333** [micronaut-projects/micronaut-starter#292]
### Description

The `gradle build` (gradle 6.5.0) failed with `Unsupported JDK version: 13.`, which prevents 2.0.0 upgrade

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

```
.io.micronaut.starter.cli.feature.server.websocket.CreateWebsocketServerSpec test creating a websocket server - java FAILED

  java.lang.IllegalArgumentException: Unsupported JDK version: 13. Supported values are [8, 9, 10, 11, 12, 13, 14]
      at io.micronaut.starter.options.JdkVersion.valueOf(JdkVersion.java:53)
      at io.micronaut.starter.util.VersionInfo.getJavaVersion(VersionInfo.java:146)
      at io.micronaut.starter.options.Options.<init>(Options.java:40)
      at io.micronaut.starter.cli.CommandFixture$Trait$Helper.generateProject(CommandFixture.groovy:29)
      at io.micronaut.starter.cli.CommandFixture$Trait$Helper.generateProject(CommandFixture.groovy:25)
      at io.micronaut.starter.cli.feature.server.websocket.CreateWebsocketServerSpec.test creating a websocket server - #language.getName()(CreateWebsocketServerSpec.groovy:22)
```

full log, https://github.com/Homebrew/homebrew-core/pull/56990/checks?check_run_id=815277272#step:6:356

### Expected Behaviour

`gradle build should pass`

### Actual Behaviour

failed with the `Unsupported JDK version: 13` errors

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.0.0
- **JDK Version:** OpenJDK 13

### Example Application

relates to https://github.com/Homebrew/homebrew-core/pull/56990

**Comment by ctash** [comment]
This is not isolated to gradle 6.5.0, I just had it fail for the same reason with 6.4.1 and 6.5.1 (released today)

**Comment by alvarosanchez** [comment]
We support up to 15 now.
