### ISSUE TITLE
Kotlin + JPA should add the "org.jetbrains.kotlin.plugin.jpa" plugin to the build

### ISSUE THREAD

**Issue by matwjones** [micronaut-projects/micronaut-starter#524]
Just a quick note on this before hand.
Both java & kotlin applications (in the repos at the bottom of the description) provided were generated using [Micronaut Launch](https://micronaut.io/launch/), but I have encountered these issues from manually created modules.
Essentially, the issue seems to be with some kotlin implementation of a library.

When starting the application, it is unable to create a session to the database & is throwing an error.
Whereas the exact same structure, pojos, configuration etc with a java application seems to be working just fine.

### Repos

- [Kotlin Version](https://github.com/matwjones/mn-kotlin-jpa-bug) (not working)
- [Java Version](https://github.com/matwjones/mn-java-jpa-bug) (working)

### Steps to Reproduce

1. Start the application (I'm using an application startup listener to start a retrieve / insert)

### Expected Behaviour

Hibernate / jpa session should connect to the postgres database & successfully query & create

### Actual Behaviour

Server is unable to start & the following stack trace is thrown:
```
09:42:57.279 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [sessionFactory] of class: io.micronaut.transaction.hibernate5.HibernateTransactionManager

Message: No bean of type [org.hibernate.SessionFactory] exists for the given qualifier: @Named('default'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new HibernateTransactionManager([SessionFactory sessionFactory],DataSource dataSource,Interceptor entityInterceptor)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [sessionFactory] of class: io.micronaut.transaction.hibernate5.HibernateTransactionManager

Message: No bean of type [org.hibernate.SessionFactory] exists for the given qualifier: @Named('default'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new HibernateTransactionManager([SessionFactory sessionFactory],DataSource dataSource,Interceptor entityInterceptor)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1048)
	at io.micronaut.transaction.hibernate5.$HibernateTransactionManagerDefinition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:133)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1814)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2549)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2535)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2222)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2196)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1218)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:713)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:126)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1814)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2549)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2535)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2222)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2196)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:708)
	at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:121)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:78)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:106)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at com.example.repository.RequestRepository$Intercepted.existsByKey(Unknown Source)
	at com.example.init.DataLoader.onApplicationEvent(DataLoader.kt:31)
	at com.example.init.DataLoader.onApplicationEvent(DataLoader.kt:16)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1248)
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:494)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:340)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:109)
	at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
	at com.example.Application.main(Application.kt:12)
```

### Environment Information

- **Operating System**: MacOs Catalina
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** 11

**Comment by graemerocher** [comment]
The fix here is that Micronaut CLI or Launch should add the `"org.jetbrains.kotlin.plugin.jpa"` plugin if JPA/Hibernate is used with Kotlin

**Comment by wetted** [comment]
The example Kotlin project fails because it defines `UserDetails` as `@Entity` without an `@Id` property. The Java version defines it as an `@Introspected` DTO. In the Kotlin version, if `UserDetails` is changed to to match the Java definition, or if `@Id @GeneratedValue(strategy = GenerationType.IDENTITY) var id: Long? = null` is added then the project runs, regardless of including the "org.jetbrains.kotlin.plugin jpa"

Nevertheless, it makes sense to include the plugin for Kotlin projects that include the `data-jpa` feature, so I am adding that in https://github.com/micronaut-projects/micronaut-starter/pull/570
