### ISSUE TITLE
Starter for Azure Functions Broken for Java 11

### ISSUE THREAD

**Issue by LPalmerMSI** [micronaut-projects/micronaut-starter#711]
Using Launch to generate a sample Azure Function for Java 11 produces an function app that will not run.  When trying to access the /api/demo URI the application generates the following error:

**NOTE This application works as expected in Java 8.  Java 11 is now GA in Azure.**

[3/19/2021 11:34:16 PM] Generating 1 job function(s)
[3/19/2021 11:34:16 PM] [INFO] {DefaultClassLoaderProvider.addUrl}: Loading file URL: file:/C:/Users/lonpa/Desktop/example/build/azure-functions/demo/demo-0.1.jar
[3/19/2021 11:34:16 PM] Worker failed to function id e541166d-b464-46fc-80af-d119ba4eec9b.
[3/19/2021 11:34:16 PM] Result: Failure
Exception: ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
Stack: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.reflect.DefaultClassLoaderProvider.addUrlToSystemClassLoader(DefaultClassLoaderProvider.java:72)
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.reflect.DefaultClassLoaderProvider.addUrl(DefaultClassLoaderProvider.java:62)
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.addSearchPathsToClassLoader(JavaFunctionBroker.java:64)
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:33)
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[3/19/2021 11:34:16 PM] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)

Steps to Reproduce:
1) Generate a launch application with the following configuration:
- Application Type: Micronaut Application 
- Java Version: 11
- Micronaut Version: 2.4.1
- Language: Java
- Build: Gradle
- Test Framework: Spock
2) Open the project in IntellijIDEA
3) From the Terminal: gradlew clean azureFunctionsRun
- Function will run
4) navigate to http://localhost:7071/api/demo
- server sends 500 and the above exception is generated

Expectation:
Starter project should work out of the box.

Environment:
Windows 10 Professional

IntellijIDEA 
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 25, 2021

Java:
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

Azure Functions Core Tools:
3.0.2245

![image](https://user-images.githubusercontent.com/72145572/111852100-bf196b80-88e3-11eb-8c87-1f53ea2542f0.png)

![image](https://user-images.githubusercontent.com/72145572/111852156-ecfeb000-88e3-11eb-9084-19d37a0eda65.png)

![image](https://user-images.githubusercontent.com/72145572/111852374-ac536680-88e4-11eb-8683-09e62011df92.png)

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
