### ISSUE TITLE
when using multi-tenancy-gorm to generate a project, the multiple datasources in application.yml has a typo

### ISSUE THREAD

**Issue by zearic** [micronaut-projects/micronaut-starter#821]
### Description

when using multi-tenancy-gorm to generate a project, the multiple datasources in application.yml has a typo. It should be 'dataSources' instead of 'datasources'

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use following command to generate a project:
_curl --location --request GET 'https://launch.micronaut.io/create/default/io.sitebot.site.multitenancy?lang=GROOVY&build=GRADLE&test=SPOCK&javaVersion=JDK_8&features=multi-tenancy-gorm&features=hibernate-gorm&features=postgres' --output multitenancy.zip_

or 

_mn create-app --build=gradle --jdk=8 --lang=groovy --test=spock --features=multi-tenancy-gorm,hibernate-gorm,postgres io.sitebot.site.multitenancy_

2. check the application.yml file generated
3. the dataSources section for multiple datasources named "datasources" instead of "dataSources"
4. this will cause the datasources defined cannot be found

### Expected Behaviour

datasources defined should be found by the application

### Actual Behaviour

got error:
23:22:17.166 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: DataSource not found for name [sherlock] in configuration. Please check your multiple data sources configuration and try again.
org.grails.datastore.mapping.core.exceptions.ConfigurationException: DataSource not found for name [sherlock] in configuration. Please check your multiple data sources configuration and try again.
	at org.grails.orm.hibernate.HibernateDatastore.getDatastoreForConnection(HibernateDatastore.java:359)
	at org.grails.orm.hibernate.HibernateDatastore.getDatastoreForConnection(HibernateDatastore.java:85)
	at org.grails.orm.hibernate.AbstractHibernateDatastore.withNewSession(AbstractHibernateDatastore.java:366)
	at grails.gorm.multitenancy.Tenants$_withId_closure2.doCall(Tenants.groovy:258)
	at grails.gorm.multitenancy.Tenants$_withId_closure2.call(Tenants.groovy)
	at grails.gorm.multitenancy.Tenants$CurrentTenant.withTenant(Tenants.groovy:358)
	at grails.gorm.multitenancy.Tenants.withId(Tenants.groovy:236)
	at grails.gorm.multitenancy.Tenants.withId(Tenants.groovy:169)

### Environment Information

- **Operating System**: linux
- **Micronaut Version:** 2.5.4
- **JDK Version:** 1.8

### Example Application

curl --location --request GET 'https://launch.micronaut.io/create/default/io.sitebot.site.multitenancy?lang=GROOVY&build=GRADLE&test=SPOCK&javaVersion=JDK_8&features=multi-tenancy-gorm&features=hibernate-gorm&features=postgres' --output multitenancy.zip

or 

mn create-app --build=gradle --jdk=8 --lang=groovy --test=spock --features=multi-tenancy-gorm,hibernate-gorm,postgres io.sitebot.site.multitenancy

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
