### ISSUE TITLE
Generated JPA Project Fails To Launch

### ISSUE THREAD

**Issue by opticyclic** [micronaut-projects/micronaut-starter#896]
I generated a project using https://micronaut.io/launch but it fails to launch with a JPA error when using `./gradlew run`.

```
Caused by: io.micronaut.context.exceptions.ConfigurationException: Entities not found for JPA configuration: 'default' within packages [com.github.opticyclic.micronaut]. Check that you have correctly specified a package containing JPA entities within the "jpa.default.entity-scan.packages" property in your application configuration and that those entities are either compiled with Micronaut or a build time index produced with @Introspected(packages="foo.bar", includedAnnotations=Entity.class) declared on your Application class
        at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateMetadataSources(EntityManagerFactoryBean.java:167)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateMetadataSources1Definition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:118)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:132)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
        ... 30 common frames omitted
```

See below for the micronaut-cli.yml generated from the website:

    applicationType: default
    defaultPackage: com.github.opticyclic.micronaut
    testFramework: junit
    sourceLanguage: java
    buildTool: gradle
    features: [app-name, data, data-jpa, gradle, h2, hibernate-jpa, http-client, java, java-application, jdbc-hikari, junit, logback, netty-server, readme, shade, yaml]

**Comment by sdelamo** [comment]
When using Micronaut Data JPA you have to specify the entities package for Hibernate: 

```
jpa:
  default:
    entity-scan:
      packages:
        - 'com.example.entities'
```

**Comment by romannaglic** [comment]
And at least one `@Entity` class has to be added to the project.
