### ISSUE TITLE
Project created using the CLI with aws-lambda and security-jwt causes a hostname runtime error

### ISSUE THREAD

**Issue by aentwist** [micronaut-projects/micronaut-starter#948]
### Description

When creating a project via `mn create-app` with the aws-lambda and security-jwt features, the app fails. This error does not occur when using either apart from the other. Note that this might be an issue with either the aws-lambda or security-jwt features themselves (probably aws-lambda). I have started it here in case it is a configuration issue when using both together.

There is a [similar hostname issue on core](https://github.com/micronaut-projects/micronaut-core/issues/1806) that has been closed.

This issue is actually shown by the generated tests - which fail out of the box.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a project with aws-lambda and security-jwt

```shell
mn create-app --features aws-lambda,security-jwt com.example.borg.borg
```

2. Run the app

```shell
cd borg && ./gradlew run
```

3. Visit [localhost:8080](http://localhost:8080)

### Expected Behaviour

20x, 401 Unauthorized, 403 Forbidden, or 404 Not Found

### Actual Behaviour

500 Internal Server Error

```
15:11:04.623 [qtp1333564772-53] ERROR i.m.f.a.p.AbstractLambdaContainerHandler - Error while handling request
java.lang.IllegalArgumentException: hostname can't be null
        at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
        at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getRemoteAddress(MicronautAwsProxyRequest.java:226)
        at io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:84)
        at io.micronaut.security.filters.SecurityFilter.lambda$checkRules$6(SecurityFilter.java:167)
        at io.micronaut.security.filters.SecurityFilter$$Lambda$788/0x0000000000000000.apply(Unknown Source)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:375)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:292)
        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        at reactor.core.publisher.Mono.block(Mono.java:1703)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$9(MicronautLambdaContainerHandler.java:416)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler$$Lambda$766/0x0000000000000000.run(Unknown Source)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:278)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:80)
java.lang.IllegalArgumentException: hostname can't be null
        at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:205)
        at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
        at io.micronaut.function.aws.proxy.MicronautLambdaHandler.handleRequest(MicronautLambdaHandler.java:68)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
        at io.micronaut.function.aws.proxy.test.AwsApiProxyTestServer$AwsProxyHandler.handle(AwsApiProxyTestServer.java:201)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getRemoteAddress(MicronautAwsProxyRequest.java:226)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:84)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at io.micronaut.security.filters.SecurityFilter.lambda$checkRules$6(SecurityFilter.java:167)
        at org.eclipse.jetty.server.HttpChannel$$Lambda$557/0x0000000000000000.dispatch(Unknown Source)
        at io.micronaut.security.filters.SecurityFilter$$Lambda$788/0x0000000000000000.apply(Unknown Source)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:375)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)

        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
        at java.base/java.lang.Thread.run(Thread.java:836)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        Suppressed: java.lang.Exception: #block terminated with an error
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
                at reactor.core.publisher.Mono.block(Mono.java:1704)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181)
                ... 21 common frames omitted
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
15:11:04.623 [qtp1333564772-53] ERROR c.a.s.proxy.AwsProxyExceptionHandler - Called exception handler for:
        at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
java.lang.IllegalArgumentException: hostname can't be null
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
        at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getRemoteAddress(MicronautAwsProxyRequest.java:226)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:84)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
        at io.micronaut.security.filters.SecurityFilter.lambda$checkRules$6(SecurityFilter.java:167)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at io.micronaut.security.filters.SecurityFilter$$Lambda$788/0x0000000000000000.apply(Unknown Source)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:292)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:375)
        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
        at reactor.core.publisher.Mono.block(Mono.java:1703)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$9(MicronautLambdaContainerHandler.java:416)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler$$Lambda$766/0x0000000000000000.run(Unknown Source)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:278)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:80)
        at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
        at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:205)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at io.micronaut.function.aws.proxy.MicronautLambdaHandler.handleRequest(MicronautLambdaHandler.java:68)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
        at io.micronaut.function.aws.proxy.test.AwsApiProxyTestServer$AwsProxyHandler.handle(AwsApiProxyTestServer.java:201)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
        at org.eclipse.jetty.server.HttpChannel$$Lambda$557/0x0000000000000000.dispatch(Unknown Source)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:292)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at reactor.core.publisher.Mono.block(Mono.java:1703)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$9(MicronautLambdaContainerHandler.java:416)
        at java.base/java.lang.Thread.run(Thread.java:836)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler$$Lambda$766/0x0000000000000000.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:278)
                at reactor.core.publisher.Mono.block(Mono.java:1704)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:80)
                ... 21 more
        at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:205)
        at io.micronaut.function.aws.proxy.MicronautLambdaHandler.handleRequest(MicronautLambdaHandler.java:68)
        at io.micronaut.function.aws.proxy.test.AwsApiProxyTestServer$AwsProxyHandler.handle(AwsApiProxyTestServer.java:201)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel$$Lambda$557/0x0000000000000000.dispatch(Unknown Source)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:836)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1704)
                ... 21 common frames omitted
```

##### Operating System

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

Also tested on the openjdk:17-alpine image

##### Micronaut Version

SDKMAN build

```shell
$ mn -V
Micronaut Version: 3.1.0
```

##### JDK Version

11.0.11.j9 Adopt build (SDKMAN 11.0.11.j9-adpt)

```shell
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Linux amd64-64-Bit Compressed References 20210421_975 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)
```

Also tested with a Java 17 Coretto build

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by aentwist** [comment]
If this cannot be reproduced with minimal effort please let me know.

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
